## Importing modules and fetching user data

In [15]:
import getpass
user= (getpass.getuser())
print("Hello", user)
import glob
base='C:\\Users\\{}\\Dropbox\\CPLab'.format(user)
print('base = ', base)

savepath = base+'\\results\\'
print('plots and stuff will be at', savepath)

Hello sinha
base =  C:\Users\sinha\Dropbox\CPLab
filtered files will be stored at C:\Users\sinha\Dropbox\CPLab\all_data_filtered_mat\
plots and stuff will be at C:\Users\sinha\Dropbox\CPLab\results\


## 

In [16]:
import pandas as pd

filter_data=pd.read_excel("C:\\Users\\{}\\Dropbox\\CPLab\\filecheck.xlsx".format(user))
filter_data = filter_data.dropna(axis=1, how='all')
filter_data = filter_data.dropna(axis=0, how='all')

filter_data = filter_data.drop(filter_data.columns[-1],axis=1)
filter_data.reset_index(drop=True, inplace=True)
filter_data.columns=['file','LFP1_AON', 'LFP2_AON', 'LFP3_AON', 'LFP4_AON','LFP1_vHp','LFP2_vHp','date' ]

In [25]:
import os
import numpy as np
filter_data_files=list(filter_data['file'])
filter_base_names_without_ext = [os.path.splitext(os.path.basename(file))[0] for file in filter_data_files]
print(filter_base_names_without_ext)
filter_data['file']=filter_base_names_without_ext
filter_data_annotations=filter_data.iloc[:,1:6]
filter_data_annotations=np.array(filter_data_annotations)
print(np.unique(filter_data_annotations))

['20230626_dk1_BW_context_day1', '20230627_dk1_BW_context_day2', '20230817_dk1_BW_context_os2_day1_pt1', '20230818_dk1_BW_context_os2_day2', '20230623_dk1_BW_context_day1', '20230609_dk1_BW_nocontext_day1', '20230609_dk1_BW_nocontext_day2', '20230817_dk1_BW_context_os2_day1_pt2', '20230822_dk1_BW_nocontext_os2_day2', '20230610_dk1_BW_nocontext_day2', '20230822_dk1_BW_nocontext_os2_day1', '20230823_dk1_BW_nocontext_os2_day2', '20230529_dk1_nocontext', '20230531_dk1_nocontext_day2', '20230718_dk1_nocontext_os2', '20230719_dk1_nocontext_os2_day2_part1', '20230719_dk1_nocontext_os2_day2_part2', '20230807_dk3_BW_context_day1', '20230808_dk3_BW_context_day2', '20230818_dk3_BW_context_os2_day1', '20230821_dk3_BW_context_os2_day2', '20230609_dk3_BW_nocontext_day1', '20230610_dk3_BW_nocontext_day2', '20230529_dk3_nocontext', '20230531_dk3_nocontext_day2', '20230615_dk6_BW_context_day1', '20230616_dk6_BW_context_day2', '20230626_dk6_BW_nocontext_day1', '20230628_dk6_BW_nocontext_day2', '20230529

In [18]:
import glob
files = glob.glob(r'C:\Users\sinha\Dropbox\CPLab\all_data_mat\*.mat')
print(files)

['C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230529_dk1_nocontext.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230529_dk3_nocontext.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230529_dk5_nocontext.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230529_dk6_nocontext.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230531_dk1_nocontext_day2.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230531_dk3_nocontext_day2.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230531_dk5_nocontext_day2.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230531_dk6_nocontext_day2.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230609_dk1_BW_nocontext_day1.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230609_dk3_BW_nocontext_day1.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230610_dk1_BW_nocontext_day2.mat', 'C:\\Users\\sinha\\Dropbox\\CPLab\\all_data_mat\\20230610_dk3_BW_nocontext_day2.mat', 'C:\\Users\

In [19]:
print(len(files))
print(filter_data.shape)
files_list=[]
for file in files:
        base_name = os.path.basename(file)
        base_name_without_ext = os.path.splitext(base_name)[0]
        files_list.append(base_name_without_ext)
set1=set(list(files_list))
set2=set(list(filter_data['file']))

# Find the uncommon elements using symmetric difference
uncommon_elements = set1.symmetric_difference(set2)

# Convert the result back to a list (if needed)
uncommon_elements_list = list(uncommon_elements)
print(uncommon_elements_list)

43
(45, 8)
['20230609_dk1_BW_nocontext_day2', '20230822_dk1_BW_nocontext_os2_day2']


These two files dont exist and are a typo in the filecheck.xlsx file

In [26]:
channel_names=['LFP1_AON', 'LFP2_AON', 'LFP3_AON', 'LFP4_AON','LFP1_vHp','LFP2_vHp']
import h5py
import os
not_here_list=[]
for file in files:
    f=h5py.File(file, 'r+')
    try:
        base_name = os.path.basename(file)
        base_name_without_ext = os.path.splitext(base_name)[0]
        #print(base_name_without_ext)
        if base_name_without_ext in filter_base_names_without_ext:
            print(base_name_without_ext,'yes')
            row = filter_data.loc[filter_data['file'] == base_name_without_ext]
            #print(row)
            for column in row.columns:
                value = row[column].values[0]
                if value == 'no' or value=='NO':
                    print(f"Column '{column}' has value 'no'")
                    if column in f.keys():
                        del f[column]
                        print(f"Deleted key '{column}' from file '{file}'")
                elif value == 'ok' or value=='OK':
                    print(f"Column '{column}' has value 'ok'")
        
        else:
            print(base_name_without_ext, 'this file not here')
            not_here_list.append(base_name_without_ext)
    finally:
        f.close()
print(not_here_list)

20230529_dk1_nocontext yes
Column 'LFP1_AON' has value 'ok'
Column 'LFP2_AON' has value 'ok'
Column 'LFP3_AON' has value 'ok'
Column 'LFP4_AON' has value 'ok'
Column 'LFP1_vHp' has value 'ok'
Column 'LFP2_vHp' has value 'ok'
20230529_dk3_nocontext yes
Column 'LFP1_AON' has value 'no'
Deleted key 'LFP1_AON' from file 'C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk3_nocontext.mat'
Column 'LFP2_AON' has value 'no'
Deleted key 'LFP2_AON' from file 'C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk3_nocontext.mat'
Column 'LFP3_AON' has value 'no'
Deleted key 'LFP3_AON' from file 'C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk3_nocontext.mat'
Column 'LFP4_AON' has value 'no'
Deleted key 'LFP4_AON' from file 'C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk3_nocontext.mat'
Column 'LFP1_vHp' has value 'no'
Deleted key 'LFP1_vHp' from file 'C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk3_nocontext.mat'
Column 'LFP2_vHp' has value 'no'
Deleted key 'LFP2_vHp' from fi

In [29]:
for file in files:
    f=h5py.File(file, 'r')
    channels=f.keys()
    print(file, channels)
    f.close()

C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk1_nocontext.mat <KeysViewHDF5 ['Keyboard', 'LFP1_AON', 'LFP1_vHp', 'LFP2_AON', 'LFP2_vHp', 'LFP3_AON', 'LFP4_AON', 'Ref', 'Respirat', 'file']>
C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk3_nocontext.mat <KeysViewHDF5 ['Keyboard', 'Ref', 'Respirat', 'file']>
C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk5_nocontext.mat <KeysViewHDF5 ['Keyboard', 'LFP1_AON', 'LFP1_vHp', 'LFP2_AON', 'LFP2_vHp', 'LFP3_AON', 'LFP4_AON', 'Ref', 'Respirat', 'file']>
C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230529_dk6_nocontext.mat <KeysViewHDF5 ['LFP1_AON', 'LFP1_vHp', 'LFP2_AON', 'LFP2_vHp', 'LFP3_AON', 'LFP4_AON', 'Memory', 'Ref', 'Respirat', 'file']>
C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230531_dk1_nocontext_day2.mat <KeysViewHDF5 ['Keyboard', 'LFP1_AON', 'LFP1_vHp', 'LFP2_AON', 'LFP2_vHp', 'LFP3_AON', 'LFP4_AON', 'Ref', 'Respirat', 'file']>
C:\Users\sinha\Dropbox\CPLab\all_data_mat\20230531_dk3_nocontext_day2.mat <KeysViewHDF5 [

In [34]:
def decimal_to_unicode(decimal_list):
    """
    Convert a list of decimal numbers to their corresponding Unicode characters.
    
    Parameters:
    decimal_list (list): List of decimal numbers.
    
    Returns:
    list: List of Unicode characters.
    """
    return [chr(decimal) for decimal in decimal_list]

# Example usage
decimal_list = [65, 66, 67, 8364]  # A, B, C, €
unicode_characters = decimal_to_unicode(decimal_list)
print(unicode_characters)
def combine_strings(string_list, separator=''):
    """
    Combine strings in a list into a single string with an optional separator.
    
    Parameters:
    string_list (list): List of strings to combine.
    separator (str): Separator to use between strings. Default is an empty string.
    
    Returns:
    str: Combined string.
    """
    return separator.join(string_list)

# Example usage
string_list = ['Hello', 'world', 'this', 'is', 'a', 'test']
combined_string = combine_strings(string_list, ' ')
#files=['C:\\Users\\Thomas\\Dropbox\\CPLab\\all_data_mat_filtered\\20230529_dk1_nocontext.mat']
codes_all=[]
comments_all=[]
for file in files:
    f = h5py.File(file, 'r')
    channels = list(f.keys())
    #print(channels)

    if 'Keyboard' in channels:
        events = f['Keyboard']
    elif 'keyboard' in channels:
        events = f['keyboard']
    elif 'memory' in channels:
        events = f['memory']
    elif 'Memory' in channels:
        events = f['Memory']

    #print(events.keys())

    #print(events['times'][0,:])
    print(events['title'][:,0])
    print(combine_strings(decimal_to_unicode(events['title'][:,0]), ''))
    codes_all.append(np.array(events['codes'][0]))
    comments_all.append(np.array(events['comment']))
    please=decimal_to_unicode(events['comment'][:,0])
    combined_string = combine_strings(please, ' ')
    #print(combined_string)
#print(codes_all)
codes_all=np.concatenate(codes_all)
comments_all=np.concatenate(comments_all)
#print(codes_all)

codes_all_unique=np.unique(codes_all)
comments_all_unique=np.unique(comments_all)
print(codes_all_unique)
print(comments_all_unique)

['A', 'B', 'C', '€']
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 77 101 109 111 114 121]
Memory
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 77 101 109 111 114 121]
Memory
[ 77 101 109 111 114 121]
Memory
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 77 101 109 111 114 121]
Memory
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 100]
Keyboard
[ 75 101 121  98 111  97 114 1